ONBOARD_MSG = (
    "👋 **Welcome to NewsBot!**\n\n"
    "You're now registered!\n\n"
    "**Quick Setup:**\n"
    "• Set your country: `/setcountry <country_code>`\n"
    "• Set your language(s): `/setlang <lang_codes>`\n"
    "**Try these commands:**\n"
    "• `/news` — Top headlines\n"
    "• `/localnews <place>` — Local news via RSS\n"
    "• `/category <category>` — Category news\n"
    "• `/search <keyword>` — Search for news\n"
    "• `/bookmark <url> <title>` — Bookmark an article\n"
    "• `/dailynews <on|off>` — Daily news in DMs\n\n"
    "_Use `/help` any time to see all commands!_\n"
)
