services:
  - type: web
    name: news-discord-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: |
      python bot.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
